version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_vue-docker
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]